version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${RAILWAY_STATIC_URL:-http://localhost:5001}/api
    restart: always

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      - DB_TYPE=postgres
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-utility_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-secret_utility_key_for_demo_only_change_in_production}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    restart: always

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-utility_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
