services:
  - type: web
    name: utility-backend
    runtime: docker
    rootDir: backend
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 5001
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - backend/**/* 